# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 09:32
from __future__ import unicode_literals
import users.storage
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20151202_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(default='first name', max_length=30),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='profile_image',
            field=models.ImageField(blank=True, storage=users.storage.OverwriteStorage(), upload_to=users.models.profile_pic_path),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='surname',
            field=models.CharField(default='second name', max_length=30),
        ),
    ]
